# Security Settings
password-min-length: 8
# Gameplay Restrictions When Unauthenticated
block-movement: true
block-chat: true
block-commands: true
# Messages
messages:
  not-registered: "&cYou must register first! Use /register <password> <confirm>"
  not-logged-in: "&cYou must log in first! Use /login <password>"
  register-success: "&a!Chips - Successfully registered"
  login-success: "&a!Chips - Successfully logged in"
  password-mismatch: "&cPasswords do not match!"
  password-too-short: "&cPassword must be at least %length% characters!"
  account-already-exists: "&cYou already have an account!"
  password-changed: "&a!Chips - Password successfully changed"
  password-reset: "&a!Chips - Your password has been reset by an admin"
  
